### ISSUE TITLE
Subscription renewal question

### ISSUE THREAD

**Issue by kespig** [strangerstudios/pmpro-subscription-delays#1]
I would I setup a delay so that all memberships renew on the same date monthly? Such as the 5th of every month? I'm currently using "YY-M2-05" and that's not working. Please help, thanks!

**Comment by SailorMan64** [comment]
I am trying to get the same thing going.
Tried Y1-M2-01 (first of every month)
Tried YY-MM-01.
If this can work, what happens the second year? Will it jsut keep rolling?

Thanks

**Comment by SailorMan64** [comment]
Having finally found and read some more details related to the use of the Y-M-D field from here: http://www.paidmembershipspro.com/add-ons/plugins-on-github/pmpro-expiration-date/
and from the Readme file...
This is still not changing the renewal date no matter what format I use. Y-M-01 or Y-M2-01
Even Y1-M2-01 does not work.
Memberships still roll on  30 days.
Is there a way to troubleshoot this?

Thanks

**Comment by Saylrman64** [comment]
I have also tried fixed days by entering just 20. This shows the text indicating your membership will be $xxx after your free 20 day trial but the Stripe payment and trial subscription still get kicked off immediately and is for 30 days.

**Comment by SailorMan64** [comment]
I have also tried fixed days by entering just 20 days delay and it seems to work fine with or without an initial payment. 

I have since tested PMPro on a clean WP site and no plugins of any kind. The delay does not do anything. Using Y-M2-01 to get next payment to be on the first of the next month. I've tried to set it up with no initial payment as well with no luck.

Thanks

**Comment by unwiredtech** [comment]
is there a way to move the users when they are expired? or when they did not pay for their subscription?
