### ISSUE TITLE
Error with Date Output in Membership Levels

### ISSUE THREAD

**Issue by drocks13** [strangerstudios/pmpro-subscription-delays#15]
A delay of Y2-01-01 will output a starting year of 2002 on the levels page in the admin (?page=pmpro-membershiplevels) in the 'billing details' column. 

Having looked through the code briefly it looks like this setting is saved, as is, in a wordpress options i.e. saved as Y2-01-01. Then later in the plugin this function-  pmprosd_daysUntilDate($date) converts that to days from now e.g 299. As as I can tell that is how it should work.

The problem I believe occurs in the function pmprosd_level_cost_text($cost, $level) specifically this line '$cost .= " starting " . date_i18n(get_option("date_format"), strtotime($subscription_delay, current_time("timestamp"))) . ". ";' 

The variable $subscription_delay is being set with the option 'Y2-01-01" and strotime does not understand Y2. The solution would then be to convert that Y2 into a form that strotime could understand. 

That is if the add-on is meant to store the option in the Y2-01-01 format and not as something else. If so I can put in a patch to convert Y2 to a format strotime could understand but wanted to check this would not mess up anything else in the add-on/core code.

**Comment by kimcoleman** [comment]
I cannot recreate this issue. Can you explain more about the issue so that I can try to recreate?

This is what I am seeing when I set delay to Y2-01-01:
<img width="638" alt="screen shot 2018-11-08 at 9 49 07 am" src="https://user-images.githubusercontent.com/5312875/48206130-a411b680-e33b-11e8-88c5-f9e1c2bc56ce.png">

What is the date format for your site under Settings > General?

**Comment by eighty20results** [comment]
Believe this is fixed in the current release of the add-on (the updated relative date calculations)
